apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: {{ .Values.certsigningreq.user.name }}
spec:
  request: {{ .Values.certsigningreq.user.csr }}
  signerName: kubernetes.io/kube-apiserver-client
  # expirationSeconds: 86400  # one day
  usages:
  - client auth