apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rolebinding.name }}
  namespace: {{ .Values.namespace }}
subjects:
- kind: User
  name: {{ .Values.rolebinding.user.name }}
roleRef:
  kind: Role
  name: {{ .Values.rolebinding.role.name }}
  apiGroup: rbac.authorization.k8s.io
