---
namespace: dictionary-namespace

role:
  name: developer

rolebinding:
  name: read-all-resources
  user:
    name: apinya
  role:
    name: developer

certsigningreq:
  user:
    name: apinya
    csr: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZWEJwYm5saE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXlZanQxeGRmdmlFSG1aWnhMWVVmU0MxdTNOYTJVSElTVXUwRTFBVFk5RkRECnlLajAxcFRiRjJZcHlsd2hJb2kwLzBvTVg2TE5veWMrOVE2T0prc1hYb1ZVbHFqVjVTUjBaUWlLTmxMNDF3eFQKUlhDMDZHTFRlTjNkRHRHSXNaZkpLUjdkVThRQzRJQkozQ25IQXhyOE9mbXhFbzdTZE1velV0ZEozMUYzU09HaQpReXJJdWNackNFa0dBZUtBUFpmOE9pbERMSVk2aWo2NVZmcnlaYkV3VkExNUl1dWIzbFNzazZqMFVBRnlBN2FSClFpUjA4aW5zbitENWJFZDVja1VaS0s4WEszWWdvblpsRzF6dDlSWDQyRHpFMzJ6eHp0WGhvTHY2R3VoWUZqNm4KUjArNnlYcC9QeWhvaGlEazU2eVU2T1hTcC84eWJKOUZPWDA1dWNaMzhRSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBSE45bjl2ekFvMmsrWFhESjhtRmFSOFpZNkYrQ3JrZWxPOGtTWjZYU0hzS3FQbUU1NkdnClZLdmV1VXNNbUN1VnVwQzBLWFlzZ2xHMVZEd3JUSXJtU1hldDZjSEVvWkdKakgrMWxMQXBkMG9pdnh4UmdOVXAKS3lUMmViQ1UwV21XMVU4QVVkeDBzRm5qcDlZN1JMcHR2VDlWRVRFUTF0RURDNTlhVmxLS3pnWFJqaEdGTEVacwpOZ2pYazJuUGE2KzAvaklGazJJaVU5M2pTVUVRb0laeDVSbjZoYk9qY0hZMjBodkNDZzF6azVLNE5CMzJaVktOCktwNmllVGhzRDg3a1d4NjV1Slk0eG5CQTJxbHBIWFdjMlEvTFFrclJhK1dlSlF0Tis1VG84M3ZSM25odHlzQmMKWDg3RmR2VTZaQXJIMGtRK1lmTDJna0g2Z2NhZVkwUlV3UFk9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=