apiVersion: apps/v1
kind: Deployment
metadata:
  name: dictionary-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: dictionary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dictionary
  template:
    metadata:
      labels:
        app: dictionary
    spec:
      containers:
      - name: dictionary
        image: "{{ .Values.dictionary.image }}:{{ .Values.dictionary.tag }}"
        env:
        - name: MONGODB_HOST
          valueFrom:
            configMapKeyRef:
              name: dic-config
              key: mongodb_host
        - name: MONGODB_PORT
          valueFrom:
            configMapKeyRef:
              name: dic-config
              key: mongodb_port
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: secret-mongo-auth
              key: username
        - name: MONGODB_PWD
          valueFrom:
            secretKeyRef:
              name: secret-mongo-auth
              key: password
        ports:
        - containerPort: 8088
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          tcpSocket:
            port: 8088
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /search?word=yell
            port: 8088
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 2
          timeoutSeconds: 4
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 254Mi
